version: '3.8'

services:
  postgres:
    container_name: citronix-db
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: citronix
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local