spring:
  application:
    name: citronixFarm

  datasource:
    url: jdbc:postgresql://localhost:5433/citronix
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: false

server:
  port: 8080

